'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace HIT_productData
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ProductObjectControllerBinding", [Namespace]:="urn:ProductObjectControllerwsdl"),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(ProductArtTemplate)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(ProductSize)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(ProductSetupData)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(ProductColorData)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(QuantityData)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(SalesData)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(ProductLastModified)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(PricingGrid))>  _
    Partial Public Class ProductObjectControllerService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private getInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getLastModifiedOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getTopSellersOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getColorsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getSetupChargesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getImagesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getProductSizesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getProductArtTemplatesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.PODO_DETAIL.My.MySettings.Default.PODO_DETAIL_HIT_productData_ProductObjectControllerService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event getInfoCompleted As getInfoCompletedEventHandler
        
        '''<remarks/>
        Public Event getLastModifiedCompleted As getLastModifiedCompletedEventHandler
        
        '''<remarks/>
        Public Event getTopSellersCompleted As getTopSellersCompletedEventHandler
        
        '''<remarks/>
        Public Event getColorsCompleted As getColorsCompletedEventHandler
        
        '''<remarks/>
        Public Event getSetupChargesCompleted As getSetupChargesCompletedEventHandler
        
        '''<remarks/>
        Public Event getImagesCompleted As getImagesCompletedEventHandler
        
        '''<remarks/>
        Public Event getProductSizesCompleted As getProductSizesCompletedEventHandler
        
        '''<remarks/>
        Public Event getProductArtTemplatesCompleted As getProductArtTemplatesCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ProductObjectControllerwsdl#getInfo", RequestNamespace:="urn:ProductObjectControllerwsdl", ResponseNamespace:="urn:ProductObjectControllerwsdl")>  _
        Public Function getInfo(ByVal customerNumber As String, ByVal userCredential As String, ByVal productNumber As String, ByVal outlet As Boolean) As <System.Xml.Serialization.SoapElementAttribute("return")> ProductInfo
            Dim results() As Object = Me.Invoke("getInfo", New Object() {customerNumber, userCredential, productNumber, outlet})
            Return CType(results(0),ProductInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getInfoAsync(ByVal customerNumber As String, ByVal userCredential As String, ByVal productNumber As String, ByVal outlet As Boolean)
            Me.getInfoAsync(customerNumber, userCredential, productNumber, outlet, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getInfoAsync(ByVal customerNumber As String, ByVal userCredential As String, ByVal productNumber As String, ByVal outlet As Boolean, ByVal userState As Object)
            If (Me.getInfoOperationCompleted Is Nothing) Then
                Me.getInfoOperationCompleted = AddressOf Me.OngetInfoOperationCompleted
            End If
            Me.InvokeAsync("getInfo", New Object() {customerNumber, userCredential, productNumber, outlet}, Me.getInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OngetInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.getInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getInfoCompleted(Me, New getInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ProductObjectControllerwsdl#getLastModified", RequestNamespace:="urn:ProductObjectControllerwsdl", ResponseNamespace:="urn:ProductObjectControllerwsdl")>  _
        Public Function getLastModified(ByVal customerNumber As String, ByVal userCredential As String) As <System.Xml.Serialization.SoapElementAttribute("return")> ProductLastModified()
            Dim results() As Object = Me.Invoke("getLastModified", New Object() {customerNumber, userCredential})
            Return CType(results(0),ProductLastModified())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getLastModifiedAsync(ByVal customerNumber As String, ByVal userCredential As String)
            Me.getLastModifiedAsync(customerNumber, userCredential, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getLastModifiedAsync(ByVal customerNumber As String, ByVal userCredential As String, ByVal userState As Object)
            If (Me.getLastModifiedOperationCompleted Is Nothing) Then
                Me.getLastModifiedOperationCompleted = AddressOf Me.OngetLastModifiedOperationCompleted
            End If
            Me.InvokeAsync("getLastModified", New Object() {customerNumber, userCredential}, Me.getLastModifiedOperationCompleted, userState)
        End Sub
        
        Private Sub OngetLastModifiedOperationCompleted(ByVal arg As Object)
            If (Not (Me.getLastModifiedCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getLastModifiedCompleted(Me, New getLastModifiedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ProductObjectControllerwsdl#getTopSellers", RequestNamespace:="urn:ProductObjectControllerwsdl", ResponseNamespace:="urn:ProductObjectControllerwsdl")>  _
        Public Function getTopSellers(ByVal customerNumber As String, ByVal userCredential As String, <System.Xml.Serialization.SoapElementAttribute(DataType:="integer")> ByVal count As String) As <System.Xml.Serialization.SoapElementAttribute("return")> ProductTopSellers
            Dim results() As Object = Me.Invoke("getTopSellers", New Object() {customerNumber, userCredential, count})
            Return CType(results(0),ProductTopSellers)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getTopSellersAsync(ByVal customerNumber As String, ByVal userCredential As String, ByVal count As String)
            Me.getTopSellersAsync(customerNumber, userCredential, count, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getTopSellersAsync(ByVal customerNumber As String, ByVal userCredential As String, ByVal count As String, ByVal userState As Object)
            If (Me.getTopSellersOperationCompleted Is Nothing) Then
                Me.getTopSellersOperationCompleted = AddressOf Me.OngetTopSellersOperationCompleted
            End If
            Me.InvokeAsync("getTopSellers", New Object() {customerNumber, userCredential, count}, Me.getTopSellersOperationCompleted, userState)
        End Sub
        
        Private Sub OngetTopSellersOperationCompleted(ByVal arg As Object)
            If (Not (Me.getTopSellersCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getTopSellersCompleted(Me, New getTopSellersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ProductObjectControllerwsdl#getColors", RequestNamespace:="urn:ProductObjectControllerwsdl", ResponseNamespace:="urn:ProductObjectControllerwsdl")>  _
        Public Function getColors(ByVal customerNumber As String, ByVal userCredential As String, ByVal productNumber As String) As <System.Xml.Serialization.SoapElementAttribute("return")> ProductColorData()
            Dim results() As Object = Me.Invoke("getColors", New Object() {customerNumber, userCredential, productNumber})
            Return CType(results(0),ProductColorData())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getColorsAsync(ByVal customerNumber As String, ByVal userCredential As String, ByVal productNumber As String)
            Me.getColorsAsync(customerNumber, userCredential, productNumber, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getColorsAsync(ByVal customerNumber As String, ByVal userCredential As String, ByVal productNumber As String, ByVal userState As Object)
            If (Me.getColorsOperationCompleted Is Nothing) Then
                Me.getColorsOperationCompleted = AddressOf Me.OngetColorsOperationCompleted
            End If
            Me.InvokeAsync("getColors", New Object() {customerNumber, userCredential, productNumber}, Me.getColorsOperationCompleted, userState)
        End Sub
        
        Private Sub OngetColorsOperationCompleted(ByVal arg As Object)
            If (Not (Me.getColorsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getColorsCompleted(Me, New getColorsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ProductObjectControllerwsdl#getSetupCharges", RequestNamespace:="urn:ProductObjectControllerwsdl", ResponseNamespace:="urn:ProductObjectControllerwsdl")>  _
        Public Function getSetupCharges(ByVal customerNumber As String, ByVal userCredential As String, ByVal productNumber As String) As <System.Xml.Serialization.SoapElementAttribute("return")> ProductSetupData()
            Dim results() As Object = Me.Invoke("getSetupCharges", New Object() {customerNumber, userCredential, productNumber})
            Return CType(results(0),ProductSetupData())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getSetupChargesAsync(ByVal customerNumber As String, ByVal userCredential As String, ByVal productNumber As String)
            Me.getSetupChargesAsync(customerNumber, userCredential, productNumber, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getSetupChargesAsync(ByVal customerNumber As String, ByVal userCredential As String, ByVal productNumber As String, ByVal userState As Object)
            If (Me.getSetupChargesOperationCompleted Is Nothing) Then
                Me.getSetupChargesOperationCompleted = AddressOf Me.OngetSetupChargesOperationCompleted
            End If
            Me.InvokeAsync("getSetupCharges", New Object() {customerNumber, userCredential, productNumber}, Me.getSetupChargesOperationCompleted, userState)
        End Sub
        
        Private Sub OngetSetupChargesOperationCompleted(ByVal arg As Object)
            If (Not (Me.getSetupChargesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getSetupChargesCompleted(Me, New getSetupChargesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ProductObjectControllerwsdl#getImages", RequestNamespace:="urn:ProductObjectControllerwsdl", ResponseNamespace:="urn:ProductObjectControllerwsdl")>  _
        Public Function getImages(ByVal customerNumber As String, ByVal userCredential As String, ByVal productNumber As String) As <System.Xml.Serialization.SoapElementAttribute("return")> ProductImageResult
            Dim results() As Object = Me.Invoke("getImages", New Object() {customerNumber, userCredential, productNumber})
            Return CType(results(0),ProductImageResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getImagesAsync(ByVal customerNumber As String, ByVal userCredential As String, ByVal productNumber As String)
            Me.getImagesAsync(customerNumber, userCredential, productNumber, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getImagesAsync(ByVal customerNumber As String, ByVal userCredential As String, ByVal productNumber As String, ByVal userState As Object)
            If (Me.getImagesOperationCompleted Is Nothing) Then
                Me.getImagesOperationCompleted = AddressOf Me.OngetImagesOperationCompleted
            End If
            Me.InvokeAsync("getImages", New Object() {customerNumber, userCredential, productNumber}, Me.getImagesOperationCompleted, userState)
        End Sub
        
        Private Sub OngetImagesOperationCompleted(ByVal arg As Object)
            If (Not (Me.getImagesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getImagesCompleted(Me, New getImagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ProductObjectControllerwsdl#getProductSizes", RequestNamespace:="urn:ProductObjectControllerwsdl", ResponseNamespace:="urn:ProductObjectControllerwsdl")>  _
        Public Function getProductSizes(ByVal customerNumber As String, ByVal userCredential As String, ByVal productNumber As String) As <System.Xml.Serialization.SoapElementAttribute("return")> ProductSize()
            Dim results() As Object = Me.Invoke("getProductSizes", New Object() {customerNumber, userCredential, productNumber})
            Return CType(results(0),ProductSize())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getProductSizesAsync(ByVal customerNumber As String, ByVal userCredential As String, ByVal productNumber As String)
            Me.getProductSizesAsync(customerNumber, userCredential, productNumber, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getProductSizesAsync(ByVal customerNumber As String, ByVal userCredential As String, ByVal productNumber As String, ByVal userState As Object)
            If (Me.getProductSizesOperationCompleted Is Nothing) Then
                Me.getProductSizesOperationCompleted = AddressOf Me.OngetProductSizesOperationCompleted
            End If
            Me.InvokeAsync("getProductSizes", New Object() {customerNumber, userCredential, productNumber}, Me.getProductSizesOperationCompleted, userState)
        End Sub
        
        Private Sub OngetProductSizesOperationCompleted(ByVal arg As Object)
            If (Not (Me.getProductSizesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getProductSizesCompleted(Me, New getProductSizesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ProductObjectControllerwsdl#getProductArtTemplates", RequestNamespace:="urn:ProductObjectControllerwsdl", ResponseNamespace:="urn:ProductObjectControllerwsdl")>  _
        Public Function getProductArtTemplates(ByVal customerNumber As String, ByVal userCredential As String, ByVal productNumber As String) As <System.Xml.Serialization.SoapElementAttribute("return")> ProductArtTemplate()
            Dim results() As Object = Me.Invoke("getProductArtTemplates", New Object() {customerNumber, userCredential, productNumber})
            Return CType(results(0),ProductArtTemplate())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getProductArtTemplatesAsync(ByVal customerNumber As String, ByVal userCredential As String, ByVal productNumber As String)
            Me.getProductArtTemplatesAsync(customerNumber, userCredential, productNumber, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getProductArtTemplatesAsync(ByVal customerNumber As String, ByVal userCredential As String, ByVal productNumber As String, ByVal userState As Object)
            If (Me.getProductArtTemplatesOperationCompleted Is Nothing) Then
                Me.getProductArtTemplatesOperationCompleted = AddressOf Me.OngetProductArtTemplatesOperationCompleted
            End If
            Me.InvokeAsync("getProductArtTemplates", New Object() {customerNumber, userCredential, productNumber}, Me.getProductArtTemplatesOperationCompleted, userState)
        End Sub
        
        Private Sub OngetProductArtTemplatesOperationCompleted(ByVal arg As Object)
            If (Not (Me.getProductArtTemplatesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getProductArtTemplatesCompleted(Me, New getProductArtTemplatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:ProductObjectControllerwsdl")>  _
    Partial Public Class ProductInfo
        
        Private numberField As String
        
        Private productUrlField As String
        
        Private nameField As String
        
        Private categoriesField() As String
        
        Private descriptionsField() As String
        
        Private propertiesField() As String
        
        Private pricingGridField() As PricingGrid
        
        Private imagesField As ProductImageResult
        
        Private colorsField() As String
        
        Private weightLbsField As String
        
        Private weightPerField As String
        
        '''<remarks/>
        Public Property number() As String
            Get
                Return Me.numberField
            End Get
            Set
                Me.numberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property productUrl() As String
            Get
                Return Me.productUrlField
            End Get
            Set
                Me.productUrlField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property categories() As String()
            Get
                Return Me.categoriesField
            End Get
            Set
                Me.categoriesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property descriptions() As String()
            Get
                Return Me.descriptionsField
            End Get
            Set
                Me.descriptionsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property properties() As String()
            Get
                Return Me.propertiesField
            End Get
            Set
                Me.propertiesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property pricingGrid() As PricingGrid()
            Get
                Return Me.pricingGridField
            End Get
            Set
                Me.pricingGridField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property images() As ProductImageResult
            Get
                Return Me.imagesField
            End Get
            Set
                Me.imagesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property colors() As String()
            Get
                Return Me.colorsField
            End Get
            Set
                Me.colorsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property weightLbs() As String
            Get
                Return Me.weightLbsField
            End Get
            Set
                Me.weightLbsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property weightPer() As String
            Get
                Return Me.weightPerField
            End Get
            Set
                Me.weightPerField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:ProductObjectControllerwsdl")>  _
    Partial Public Class PricingGrid
        
        Private priceField As String
        
        Private quantityField As String
        
        Private discountField As String
        
        Private gridNameField As String
        
        '''<remarks/>
        Public Property price() As String
            Get
                Return Me.priceField
            End Get
            Set
                Me.priceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property quantity() As String
            Get
                Return Me.quantityField
            End Get
            Set
                Me.quantityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property discount() As String
            Get
                Return Me.discountField
            End Get
            Set
                Me.discountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property gridName() As String
            Get
                Return Me.gridNameField
            End Get
            Set
                Me.gridNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:ProductObjectControllerwsdl")>  _
    Partial Public Class ProductArtTemplate
        
        Private urlField As String
        
        '''<remarks/>
        Public Property url() As String
            Get
                Return Me.urlField
            End Get
            Set
                Me.urlField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:ProductObjectControllerwsdl")>  _
    Partial Public Class ProductSize
        
        Private sizeField As String
        
        '''<remarks/>
        Public Property size() As String
            Get
                Return Me.sizeField
            End Get
            Set
                Me.sizeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:ProductObjectControllerwsdl")>  _
    Partial Public Class ProductSetupData
        
        Private decoration_codeField As String
        
        Private decorationField As String
        
        Private setup_chargeField As String
        
        Private run_chargeField As String
        
        Private extra_color_chargeField As String
        
        Private extra_location_chargeField As String
        
        '''<remarks/>
        Public Property decoration_code() As String
            Get
                Return Me.decoration_codeField
            End Get
            Set
                Me.decoration_codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property decoration() As String
            Get
                Return Me.decorationField
            End Get
            Set
                Me.decorationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property setup_charge() As String
            Get
                Return Me.setup_chargeField
            End Get
            Set
                Me.setup_chargeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property run_charge() As String
            Get
                Return Me.run_chargeField
            End Get
            Set
                Me.run_chargeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property extra_color_charge() As String
            Get
                Return Me.extra_color_chargeField
            End Get
            Set
                Me.extra_color_chargeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property extra_location_charge() As String
            Get
                Return Me.extra_location_chargeField
            End Get
            Set
                Me.extra_location_chargeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:ProductObjectControllerwsdl")>  _
    Partial Public Class ProductColorData
        
        Private color_idField As String
        
        Private part_numberField As String
        
        Private product_numberField As String
        
        Private colorField As String
        
        Private is_outletField As Boolean
        
        '''<remarks/>
        Public Property color_id() As String
            Get
                Return Me.color_idField
            End Get
            Set
                Me.color_idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property part_number() As String
            Get
                Return Me.part_numberField
            End Get
            Set
                Me.part_numberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property product_number() As String
            Get
                Return Me.product_numberField
            End Get
            Set
                Me.product_numberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property color() As String
            Get
                Return Me.colorField
            End Get
            Set
                Me.colorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property is_outlet() As Boolean
            Get
                Return Me.is_outletField
            End Get
            Set
                Me.is_outletField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:ProductObjectControllerwsdl")>  _
    Partial Public Class QuantityData
        
        Private productField As String
        
        Private descriptionField As String
        
        '''<remarks/>
        Public Property product() As String
            Get
                Return Me.productField
            End Get
            Set
                Me.productField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:ProductObjectControllerwsdl")>  _
    Partial Public Class SalesData
        
        Private productField As String
        
        Private descriptionField As String
        
        '''<remarks/>
        Public Property product() As String
            Get
                Return Me.productField
            End Get
            Set
                Me.productField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:ProductObjectControllerwsdl")>  _
    Partial Public Class ProductTopSellers
        
        Private salesField() As SalesData
        
        Private quantityField() As QuantityData
        
        '''<remarks/>
        Public Property sales() As SalesData()
            Get
                Return Me.salesField
            End Get
            Set
                Me.salesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property quantity() As QuantityData()
            Get
                Return Me.quantityField
            End Get
            Set
                Me.quantityField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:ProductObjectControllerwsdl")>  _
    Partial Public Class ProductLastModified
        
        Private numberField As String
        
        Private timeModifiedField As String
        
        Private domainField As String
        
        '''<remarks/>
        Public Property number() As String
            Get
                Return Me.numberField
            End Get
            Set
                Me.numberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property timeModified() As String
            Get
                Return Me.timeModifiedField
            End Get
            Set
                Me.timeModifiedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property domain() As String
            Get
                Return Me.domainField
            End Get
            Set
                Me.domainField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:ProductObjectControllerwsdl")>  _
    Partial Public Class ProductImageResult
        
        Private allField() As String
        
        Private mainField As String
        
        '''<remarks/>
        Public Property all() As String()
            Get
                Return Me.allField
            End Get
            Set
                Me.allField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property main() As String
            Get
                Return Me.mainField
            End Get
            Set
                Me.mainField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub getInfoCompletedEventHandler(ByVal sender As Object, ByVal e As getInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ProductInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ProductInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub getLastModifiedCompletedEventHandler(ByVal sender As Object, ByVal e As getLastModifiedCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getLastModifiedCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ProductLastModified()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ProductLastModified())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub getTopSellersCompletedEventHandler(ByVal sender As Object, ByVal e As getTopSellersCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getTopSellersCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ProductTopSellers
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ProductTopSellers)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub getColorsCompletedEventHandler(ByVal sender As Object, ByVal e As getColorsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getColorsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ProductColorData()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ProductColorData())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub getSetupChargesCompletedEventHandler(ByVal sender As Object, ByVal e As getSetupChargesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getSetupChargesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ProductSetupData()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ProductSetupData())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub getImagesCompletedEventHandler(ByVal sender As Object, ByVal e As getImagesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getImagesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ProductImageResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ProductImageResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub getProductSizesCompletedEventHandler(ByVal sender As Object, ByVal e As getProductSizesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getProductSizesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ProductSize()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ProductSize())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub getProductArtTemplatesCompletedEventHandler(ByVal sender As Object, ByVal e As getProductArtTemplatesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getProductArtTemplatesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ProductArtTemplate()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ProductArtTemplate())
            End Get
        End Property
    End Class
End Namespace
